version: 0.0
os: linux
files:
  - source: ./spark-covid_2.11-1.0.jar
    destination: /tmp
  - source: ./countries_europe.csv
    destination: /tmp
  - source: ./countries_population.csv
    destination: /tmp

hooks:
    ApplicationStart:
    - location: ./home/ec2-user/spark-2.4.5-bin-hadoop2.7/bin/spark-submit --class "ReportsGenerator" --master local[1] /tmp/spark-covid_2.11-1.0.jar